/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 27/04/2021 10:17:16
*/


-- ----------------------------
-- Table structure for SCADA_REPORT_XN_MID
-- ----------------------------
DROP TABLE "SCOTT"."SCADA_REPORT_XN_MID";
CREATE TABLE "SCOTT"."SCADA_REPORT_XN_MID" (
  "SRXM_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "SRXM_ID" VARCHAR2(20 BYTE) DEFAULT '' NOT NULL ,
  "FLMETER_NO" VARCHAR2(20 BYTE) ,
  "COMM_NO" VARCHAR2(20 BYTE) ,
  "REPORT_TIME" TIMESTAMP(6) ,
  "YEAR" VARCHAR2(10 BYTE) ,
  "MONTH" VARCHAR2(10 BYTE) ,
  "DAY" VARCHAR2(10 BYTE) ,
  "STD_SUM" VARCHAR2(18 BYTE) ,
  "WORK_SUM" VARCHAR2(18 BYTE) ,
  "PRICE" VARCHAR2(18 BYTE) ,
  "THIS_CYCLE_SUM" VARCHAR2(18 BYTE) ,
  "CYCLE_USE_MONEY" VARCHAR2(18 BYTE) ,
  "THIS_DAY_SUM" VARCHAR2(18 BYTE) ,
  "SUM_TOTAL_MONEY" VARCHAR2(18 BYTE) ,
  "TOTAL_BUY_VOLUME" VARCHAR2(18 BYTE) ,
  "TOTAL_BUY_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_VOLUME" VARCHAR2(18 BYTE) ,
  "FM_STATE" VARCHAR2(50 BYTE) ,
  "BATTERY_VOLTAGE" VARCHAR2(18 BYTE) ,
  "BATTERY_LEVEL" VARCHAR2(18 BYTE) ,
  "RSSI" VARCHAR2(10 BYTE) ,
  "FM_STATE_MSG" VARCHAR2(200 BYTE)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."SRXM_ORG_ID" IS '机构号0080';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."SRXM_ID" IS '记录ID,20位，机构内连续，机构号4位，年月6位，流水10位';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."FLMETER_NO" IS '流量计编号，导入后从SCADA_FLMETER_INFO update';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."COMM_NO" IS '通讯编号，meter_comm_no';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."REPORT_TIME" IS '报表生成时间，report_gen_time';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."YEAR" IS '年（业务发生），report_year';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."MONTH" IS '月（业务发生），report_month';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."DAY" IS '日（业务发生），report_day';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."STD_SUM" IS '标况总量（期末数），std_sum';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."WORK_SUM" IS '工况总量（期末数），work_sum';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."PRICE" IS '单价（curr_price）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."THIS_CYCLE_SUM" IS '周期内标况使用量（this_cycle_sum）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."CYCLE_USE_MONEY" IS '周期内使用额（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."THIS_DAY_SUM" IS '当天用量this_day_sum';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."SUM_TOTAL_MONEY" IS '总累计使用金额（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."TOTAL_BUY_VOLUME" IS '累购气量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."TOTAL_BUY_MONEY" IS '累购金额（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."REMAIN_MONEY" IS '剩余金额（remain_money）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."REMAIN_VOLUME" IS '剩余数量（remain_volume）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."FM_STATE" IS '流量计状态，按位存放（meter_state）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."BATTERY_VOLTAGE" IS '电池电压（battery_voltage）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."BATTERY_LEVEL" IS '电池电量（battery_level）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."RSSI" IS '信号强度（rssi）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MID"."FM_STATE_MSG" IS '表状态解析（meter_stat_emsg）';
COMMENT ON TABLE "SCOTT"."SCADA_REPORT_XN_MID" IS '中间表，导入西宁远传膜表月报数据meter_report_month_yyyymm';

-- ----------------------------
-- Table structure for SCADA_REPORT_XN_MONTH
-- ----------------------------
DROP TABLE "SCOTT"."SCADA_REPORT_XN_MONTH";
CREATE TABLE "SCOTT"."SCADA_REPORT_XN_MONTH" (
  "SRXM_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "FLMETER_NO" VARCHAR2(20 BYTE) ,
  "COMM_NO" VARCHAR2(20 BYTE) NOT NULL ,
  "CUSTOMER_NO" VARCHAR2(20 BYTE) ,
  "REPORT_TIME" TIMESTAMP(6) ,
  "REPORT_BEGIN_DATE" DATE NOT NULL ,
  "BEGIN_STD_SUM" VARCHAR2(18 BYTE) ,
  "BEGIN_PRICE" VARCHAR2(18 BYTE) ,
  "BEGIN_THIS_CYCLE_SUM" VARCHAR2(18 BYTE) ,
  "REPORT_END_DATE" DATE ,
  "END_STD_SUM" VARCHAR2(18 BYTE) ,
  "END_PRICE" VARCHAR2(18 BYTE) ,
  "END_THIS_CYCLE_SUM" VARCHAR2(18 BYTE) ,
  "USE_VOLUME_STD" VARCHAR2(18 BYTE) ,
  "PRICE1_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE1_MONEY" VARCHAR2(20 BYTE) ,
  "PRICE2_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE2_MONEY" VARCHAR2(20 BYTE) ,
  "PRICE3_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE3_MONEY" VARCHAR2(20 BYTE) ,
  "USE_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_VOLUME" VARCHAR2(18 BYTE) ,
  "PRICE_NO" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE1" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME1" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE2" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME2" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE3" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME3" VARCHAR2(20 BYTE)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."SRXM_ORG_ID" IS '机构号0080';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."FLMETER_NO" IS '流量计编号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."COMM_NO" IS '通讯编号，MID表COMM_NO';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."CUSTOMER_NO" IS '西宁客户编号CUSTOMER_INFO.DEFINE_NO1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."REPORT_TIME" IS '报表生成时间';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."REPORT_BEGIN_DATE" IS '报表开始日期，1好';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."BEGIN_STD_SUM" IS '开始标况总量（期初数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."BEGIN_PRICE" IS '开始单价（curr_price）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."BEGIN_THIS_CYCLE_SUM" IS '（开始）周期内使用量（THIS_CYCLE_SUM）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."REPORT_END_DATE" IS '报表结束日期，31号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."END_STD_SUM" IS '结束标况总量（STD_SUM）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."END_PRICE" IS '结束单价（MID表PRICE）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."END_THIS_CYCLE_SUM" IS '（结束）周期内使用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."USE_VOLUME_STD" IS '标况用量，结束标况总量-开始标况总量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE1_VOLUME" IS '1阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE1_MONEY" IS '1阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE2_VOLUME" IS '2阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE2_MONEY" IS '2阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE3_VOLUME" IS '3阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE3_MONEY" IS '3阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."USE_MONEY" IS '周/月使用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."REMAIN_MONEY" IS '剩余金额（remain_money）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."REMAIN_VOLUME" IS '剩余数量（remain_volume）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."PRICE_NO" IS '价格本号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_PRICE1" IS '阶梯价格1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_VOLUME1" IS '阶量1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_PRICE2" IS '阶梯价格2';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_VOLUME2" IS '阶量2';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_PRICE3" IS '阶梯价格3';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_MONTH"."GRADE_VOLUME3" IS '阶量3';
COMMENT ON TABLE "SCOTT"."SCADA_REPORT_XN_MONTH" IS '西宁远传膜表月报结果';

-- ----------------------------
-- Table structure for SCADA_REPORT_XN_WEEK
-- ----------------------------
DROP TABLE "SCOTT"."SCADA_REPORT_XN_WEEK";
CREATE TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" (
  "SRXW_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "FLMETER_NO" VARCHAR2(20 BYTE) ,
  "COMM_NO" VARCHAR2(20 BYTE) NOT NULL ,
  "CUSTOMER_NO" VARCHAR2(20 BYTE) ,
  "REPORT_TIME" TIMESTAMP(6) ,
  "REPORT_BEGIN_DATE" DATE NOT NULL ,
  "BEGIN_STD_SUM" VARCHAR2(18 BYTE) ,
  "BEGIN_PRICE" VARCHAR2(18 BYTE) ,
  "BEGIN_THIS_CYCLE_SUM" VARCHAR2(18 BYTE) ,
  "REPORT_END_DATE" DATE ,
  "END_STD_SUM" VARCHAR2(18 BYTE) ,
  "END_PRICE" VARCHAR2(18 BYTE) ,
  "END_THIS_CYCLE_SUM" VARCHAR2(18 BYTE) ,
  "USE_VOLUME_STD" VARCHAR2(18 BYTE) ,
  "PRICE1_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE1_MONEY" VARCHAR2(20 BYTE) ,
  "PRICE2_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE2_MONEY" VARCHAR2(20 BYTE) ,
  "PRICE3_VOLUME" VARCHAR2(20 BYTE) ,
  "PRICE3_MONEY" VARCHAR2(20 BYTE) ,
  "USE_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_VOLUME" VARCHAR2(18 BYTE) ,
  "PRICE_NO" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE1" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME1" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE2" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME2" VARCHAR2(20 BYTE) ,
  "GRADE_PRICE3" VARCHAR2(20 BYTE) ,
  "GRADE_VOLUME3" VARCHAR2(20 BYTE)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."SRXW_ORG_ID" IS '机构号0080';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."FLMETER_NO" IS '流量计编号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."COMM_NO" IS '通讯编号，MID表COMM_NO';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."CUSTOMER_NO" IS '西宁客户编号CUSTOMER_INFO.DEFINE_NO1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."REPORT_TIME" IS '报表生成时间';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."REPORT_BEGIN_DATE" IS '报表开始日期，周二';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."BEGIN_STD_SUM" IS '开始标况总量（期初数）(std_sum)';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."BEGIN_PRICE" IS '开始单价（curr_price）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."BEGIN_THIS_CYCLE_SUM" IS '（开始）周期内使用量（THIS_CYCLE_SUM）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."REPORT_END_DATE" IS '报表结束日期，周一';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."END_STD_SUM" IS '结束标况总量（STD_SUM）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."END_PRICE" IS '结束单价（MID表PRICE）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."END_THIS_CYCLE_SUM" IS '（结束）周期内使用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."USE_VOLUME_STD" IS '标况用量，结束标况总量-开始标况总量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE1_VOLUME" IS '1阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE1_MONEY" IS '1阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE2_VOLUME" IS '2阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE2_MONEY" IS '2阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE3_VOLUME" IS '3阶用量';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE3_MONEY" IS '3阶用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."USE_MONEY" IS '周/月使用额';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."REMAIN_MONEY" IS '剩余金额（remain_money）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."REMAIN_VOLUME" IS '剩余数量（remain_volume）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."PRICE_NO" IS '价格本号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_PRICE1" IS '阶梯价格1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_VOLUME1" IS '阶量1';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_PRICE2" IS '阶梯价格2';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_VOLUME2" IS '阶量2';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_PRICE3" IS '阶梯价格3';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_XN_WEEK"."GRADE_VOLUME3" IS '阶量3';
COMMENT ON TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" IS '西宁远传膜表周报结果';

-- ----------------------------
-- Primary Key structure for table SCADA_REPORT_XN_MID
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086419" PRIMARY KEY ("SRXM_ORG_ID", "SRXM_ID");

-- ----------------------------
-- Checks structure for table SCADA_REPORT_XN_MID
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0076989" CHECK ("SRXM_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0076990" CHECK ("SRXM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0077294" CHECK ("SRXM_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0077295" CHECK ("SRXM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086417" CHECK ("SRXM_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086418" CHECK ("SRXM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086685" CHECK ("SRXM_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086686" CHECK ("SRXM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086696" CHECK ("SRXM_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MID" ADD CONSTRAINT "SYS_C0086697" CHECK ("SRXM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCADA_REPORT_XN_MID
-- ----------------------------
CREATE INDEX "SCOTT"."COMM_NO_XN_MID"
  ON "SCOTT"."SCADA_REPORT_XN_MID" ("COMM_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."FLMETER_NO_XN_MID"
  ON "SCOTT"."SCADA_REPORT_XN_MID" ("FLMETER_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRM_ORG_ID_XN_MID"
  ON "SCOTT"."SCADA_REPORT_XN_MID" ("SRXM_ORG_ID" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table SCADA_REPORT_XN_MONTH
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MONTH" ADD CONSTRAINT "SYS_C0086826" PRIMARY KEY ("SRXM_ORG_ID", "COMM_NO", "REPORT_BEGIN_DATE");

-- ----------------------------
-- Checks structure for table SCADA_REPORT_XN_MONTH
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MONTH" ADD CONSTRAINT "SYS_C0086824" CHECK ("COMM_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_MONTH" ADD CONSTRAINT "SYS_C0086825" CHECK ("REPORT_BEGIN_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCADA_REPORT_XN_MONTH
-- ----------------------------
CREATE INDEX "SCOTT"."COMM_NO_XN_MONTH"
  ON "SCOTT"."SCADA_REPORT_XN_MONTH" ("COMM_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."FLMETER_NO_XN_MONTH"
  ON "SCOTT"."SCADA_REPORT_XN_MONTH" ("FLMETER_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRXM_ORG_ID_MONTH"
  ON "SCOTT"."SCADA_REPORT_XN_MONTH" ("SRXM_ORG_ID" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table SCADA_REPORT_XN_WEEK
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077469" PRIMARY KEY ("SRXW_ORG_ID", "COMM_NO", "REPORT_BEGIN_DATE");

-- ----------------------------
-- Checks structure for table SCADA_REPORT_XN_WEEK
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077451" CHECK ("SRXW_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077452" CHECK ("COMM_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077453" CHECK ("REPORT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077454" CHECK ("SRXW_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077455" CHECK ("COMM_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077456" CHECK ("REPORT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077460" CHECK ("SRXW_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0077461" CHECK ("COMM_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0086811" CHECK ("SRXW_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0086812" CHECK ("COMM_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_XN_WEEK" ADD CONSTRAINT "SYS_C0086813" CHECK ("REPORT_BEGIN_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCADA_REPORT_XN_WEEK
-- ----------------------------
CREATE INDEX "SCOTT"."COMM_NO_XN_WEEK"
  ON "SCOTT"."SCADA_REPORT_XN_WEEK" ("COMM_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."FLMETER_NO_XN_WEEK"
  ON "SCOTT"."SCADA_REPORT_XN_WEEK" ("FLMETER_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRXW_ORG_ID_XN_WEEK"
  ON "SCOTT"."SCADA_REPORT_XN_WEEK" ("SRXW_ORG_ID" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
