/*
 Navicat Premium Data Transfer

 Source Server         : Oracle LMTPlat@Server
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : server:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 13/05/2019 15:44:11
*/


-- ----------------------------
-- Table structure for SCADA_REPORT_HOURLY
-- ----------------------------
DROP TABLE "SCOTT"."SCADA_REPORT_HOURLY";
CREATE TABLE "SCOTT"."SCADA_REPORT_HOURLY" (
  "SRH_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "SRH_ID" VARCHAR2(20 BYTE) DEFAULT '' NOT NULL ,
  "RTU_NO" VARCHAR2(15 BYTE) ,
  "FLMETER_NO" VARCHAR2(50 BYTE) ,
  "CUSTOMER_NO" VARCHAR2(50 BYTE) ,
  "REPORT_TIME" TIMESTAMP(6) ,
  "YEAR" VARCHAR2(10 BYTE) ,
  "MONTH" VARCHAR2(10 BYTE) ,
  "DAY" VARCHAR2(10 BYTE) ,
  "HOUR" VARCHAR2(10 BYTE) ,
  "STD_SUM" VARCHAR2(18 BYTE) ,
  "WORK_SUM" VARCHAR2(18 BYTE) ,
  "STD_FLOW" VARCHAR2(18 BYTE) ,
  "WORK_FLOW" VARCHAR2(18 BYTE) ,
  "TEMPERATURE" VARCHAR2(18 BYTE) ,
  "PRESSURE" VARCHAR2(18 BYTE) ,
  "PRICE" VARCHAR2(18 BYTE) ,
  "USE_VOLUME_WORK" VARCHAR2(18 BYTE) ,
  "USE_VOLUME_STD" VARCHAR2(18 BYTE) ,
  "USE_MONEY" VARCHAR2(18 BYTE) ,
  "SUM_TOTAL_VOLUME" VARCHAR2(18 BYTE) ,
  "SUM_TOTAL_MONEY" VARCHAR2(18 BYTE) ,
  "TOTAL_BUY_VOLUME" VARCHAR2(18 BYTE) ,
  "TOTAL_BUY_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_MONEY" VARCHAR2(18 BYTE) ,
  "REMAIN_VOLUME" VARCHAR2(18 BYTE) ,
  "FM_STATE" VARCHAR2(50 BYTE) ,
  "RTU_STATE" VARCHAR2(50 BYTE) ,
  "VALVE_STATE" VARCHAR2(10 BYTE) ,
  "POWER_VOLTAGE" VARCHAR2(18 BYTE) ,
  "BATTERY_VOLTAGE" VARCHAR2(18 BYTE) ,
  "BATTERY_LEVEL" VARCHAR2(18 BYTE) ,
  "PRESS_IN" VARCHAR2(18 BYTE) ,
  "PRESS_OUT" VARCHAR2(18 BYTE) ,
  "TEMP_IN" VARCHAR2(18 BYTE) ,
  "TEMP_OUT" VARCHAR2(18 BYTE) ,
  "RSSI" VARCHAR2(10 BYTE) ,
  "RESERVE1" VARCHAR2(50 BYTE) ,
  "RESERVE2" VARCHAR2(50 BYTE) ,
  "RESERVE3" VARCHAR2(50 BYTE) ,
  "RESERVE4" VARCHAR2(50 BYTE) ,
  "SRH_STATUS" VARCHAR2(5 BYTE) ,
  "FM_STATE_MSG" VARCHAR2(200 BYTE) ,
  "RTU_STATE_MSG" VARCHAR2(200 BYTE) ,
  "VALVE_STATE_MSG" VARCHAR2(200 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."SRH_ORG_ID" IS '机构号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."SRH_ID" IS '记录ID,20位，机构内连续，机构号4位，年月6位，流水10位';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RTU_NO" IS 'RTU编号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."FLMETER_NO" IS '流量计编号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."CUSTOMER_NO" IS '客户编号';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."REPORT_TIME" IS '报表生成时间';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."YEAR" IS '年（业务发生）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."MONTH" IS '月（业务发生）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."DAY" IS '日（业务发生）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."HOUR" IS '时（业务发生）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."STD_SUM" IS '标况总量（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."WORK_SUM" IS '工况总量（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."STD_FLOW" IS '标况流量（周期内平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."WORK_FLOW" IS '工况流量（周期内平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."TEMPERATURE" IS '温度（周期内平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."PRESSURE" IS '压力（周期内平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."PRICE" IS '单价（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."USE_VOLUME_WORK" IS '周期内工况使用量（本期期末数-上期期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."USE_VOLUME_STD" IS '周期内标况使用量（DATA表控制器总累积量 本期期末数-上期期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."USE_MONEY" IS '周期内使用额（周期内标况使用量*单价）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."SUM_TOTAL_VOLUME" IS '控制器总累积量（DATA表控制器总累积量 期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."SUM_TOTAL_MONEY" IS '总累计使用金额（NB专用，DATA表TOTAL_EXPEND_MONEY）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."TOTAL_BUY_VOLUME" IS '累购气量（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."TOTAL_BUY_MONEY" IS '累购金额（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."REMAIN_MONEY" IS '剩余金额（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."REMAIN_VOLUME" IS '剩余数量（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."FM_STATE" IS '流量计状态，按位存放（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RTU_STATE" IS 'RTU状态，按字节存放（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."VALVE_STATE" IS '阀门控制器状态（0：阀开，1：阀关）（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."POWER_VOLTAGE" IS '供电电压（周期内平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."BATTERY_VOLTAGE" IS '电池电压（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."BATTERY_LEVEL" IS '电池电量（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."PRESS_IN" IS '入口压力（周期内平均值，未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."PRESS_OUT" IS '出口压力（周期内平均值，未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."TEMP_IN" IS '入口温度（周期内平均值，未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."TEMP_OUT" IS '出口温度（周期内平均值，未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RSSI" IS '信号强度（平均值）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RESERVE1" IS '预留1(已启用，用于临时存放customername)';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RESERVE2" IS '预留2';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RESERVE3" IS '预留3';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RESERVE4" IS '预留4';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."SRH_STATUS" IS '1正常，9不正常已删除';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."FM_STATE_MSG" IS '表状态解析（按位解析）（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."RTU_STATE_MSG" IS 'RTU状态解析（按字节解析）（期末数）';
COMMENT ON COLUMN "SCOTT"."SCADA_REPORT_HOURLY"."VALVE_STATE_MSG" IS '阀门控制器状态解析（期末数）';

-- ----------------------------
-- Checks structure for table SCADA_REPORT_HOURLY
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_REPORT_HOURLY" ADD CONSTRAINT "SYS_C0049421" CHECK ("SRH_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_REPORT_HOURLY" ADD CONSTRAINT "SYS_C0049422" CHECK ("SRH_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCADA_REPORT_HOURLY
-- ----------------------------
CREATE INDEX "SCOTT"."SRH_DAY"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("DAY" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRH_FLMETER_NO"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("FLMETER_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRH_MONTH"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("MONTH" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRH_RTU_NO"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("RTU_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRH_STATUS"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("SRH_STATUS" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SRH_YEAR"
  ON "SCOTT"."SCADA_REPORT_HOURLY" ("YEAR" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
