/*
 Navicat Premium Data Transfer

 Source Server         : localhost-SCOTT
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 05/01/2022 09:15:02
*/


-- ----------------------------
-- Table structure for SCADA_FLMETER_DATA_MID_DH
-- ----------------------------
DROP TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH";
CREATE TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" (
  "SFD_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "SFD_ID" VARCHAR2(50 BYTE) NOT NULL ,
  "RTU_NO" VARCHAR2(20 BYTE) ,
  "FLMETER_NO" VARCHAR2(20 BYTE) ,
  "MESSAGE_ID" VARCHAR2(20 BYTE) ,
  "INSTANT_TIME" TIMESTAMP(6) NOT NULL ,
  "RECEIV_TIME" TIMESTAMP(6) NOT NULL ,
  "STD_SUM" VARCHAR2(20 BYTE) ,
  "WORK_SUM" VARCHAR2(20 BYTE) ,
  "STD_FLOW" VARCHAR2(20 BYTE) ,
  "WORK_FLOW" VARCHAR2(20 BYTE) ,
  "TEMPERATURE" VARCHAR2(20 BYTE) ,
  "PRESSURE" VARCHAR2(20 BYTE) ,
  "FM_STATE" VARCHAR2(50 BYTE) ,
  "FM_STATE_MSG" VARCHAR2(550 BYTE) ,
  "RTU_STATE" VARCHAR2(10 BYTE) ,
  "RTU_STATE_MSG" VARCHAR2(200 BYTE) ,
  "SUM_TOTAL" VARCHAR2(20 BYTE) ,
  "REMAIN_MONEY" VARCHAR2(20 BYTE) ,
  "REMAIN_VOLUME" VARCHAR2(20 BYTE) ,
  "OVERDRAFT" VARCHAR2(20 BYTE) ,
  "REMOTE_CHARGE_MONEY" VARCHAR2(10 BYTE) ,
  "REMOTE_CHARGE_TIMES" VARCHAR2(10 BYTE) ,
  "PRICE" VARCHAR2(10 BYTE) ,
  "VALVE_STATE" VARCHAR2(10 BYTE) ,
  "VALVE_STATE_MSG" VARCHAR2(200 BYTE) ,
  "POWER_VOLTAGE" VARCHAR2(10 BYTE) ,
  "BATTERY_VOLTAGE" VARCHAR2(10 BYTE) ,
  "RESERVE1" VARCHAR2(5 BYTE) ,
  "RESERVE2" VARCHAR2(50 BYTE) ,
  "RESERVE3" VARCHAR2(50 BYTE) ,
  "RESERVE4" VARCHAR2(50 BYTE) ,
  "AVG_STD_FLOW" VARCHAR2(10 BYTE) ,
  "AVG_WORK_FLOW" VARCHAR2(10 BYTE) ,
  "AVG_TEMPERATURE" VARCHAR2(10 BYTE) ,
  "AVG_PRESSURE" VARCHAR2(10 BYTE) ,
  "COMPUTE_DAYS" VARCHAR2(10 BYTE) ,
  "MAG_ATT_TIMES" VARCHAR2(10 BYTE) ,
  "MONTH_USE_VOL" VARCHAR2(10 BYTE) ,
  "L1_MONTH_USE_VOL" VARCHAR2(10 BYTE) ,
  "CYCLE_USE_VOL" VARCHAR2(15 BYTE) ,
  "L1_CYCLE_USE_VOL" VARCHAR2(15 BYTE) ,
  "RSSI" VARCHAR2(10 BYTE) ,
  "BATTERY_LEVEL" VARCHAR2(10 BYTE) ,
  "BASE_VOLUME" VARCHAR2(10 BYTE) ,
  "TOTAL_BUY_VOLUME" VARCHAR2(10 BYTE) ,
  "TOTAL_BUY_MONEY" VARCHAR2(10 BYTE) ,
  "EXT_DATA" VARCHAR2(300 BYTE) ,
  "CUSTOMER_NO" VARCHAR2(50 BYTE) ,
  "TOTAL_EXPEND_MONEY" VARCHAR2(10 BYTE) ,
  "SFD_STATUS" VARCHAR2(5 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
ENABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."SFD_ORG_ID" IS '机构号';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."SFD_ID" IS '流水ID';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RTU_NO" IS '所属RTU编号';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."FLMETER_NO" IS '流量计编号';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."MESSAGE_ID" IS '报文ID暂时放通讯编号';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."INSTANT_TIME" IS '采集（表头冻结）时间';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RECEIV_TIME" IS '服务器接收数据时间（上传时间）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."STD_SUM" IS '标况总量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."WORK_SUM" IS '工况总量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."STD_FLOW" IS '标况流量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."WORK_FLOW" IS '工况流量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."TEMPERATURE" IS '温度';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."PRESSURE" IS '压力';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."FM_STATE" IS '表状态（按位存放）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."FM_STATE_MSG" IS '表状态解析（按位解析）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RTU_STATE" IS 'RTU状态（按字节存放）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RTU_STATE_MSG" IS 'RTU状态解析（按字节解析）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."SUM_TOTAL" IS '控制器总累积量（卡控中存储累计用气量）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."REMAIN_MONEY" IS '剩余金额';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."REMAIN_VOLUME" IS '剩余气量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."OVERDRAFT" IS '过零金额';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."REMOTE_CHARGE_MONEY" IS '远程充值金额';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."REMOTE_CHARGE_TIMES" IS '远程充值次数（十进制）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."PRICE" IS '单价，抄表的时候同时更新INFO基础表的CURRENT_PRICE';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."VALVE_STATE" IS '阀门控制器状态（00普开，01普关，02异常,04开阀中,05关阀中，06强开，07强关）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."VALVE_STATE_MSG" IS '阀门控制器状态解析';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."POWER_VOLTAGE" IS '外供电电压';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."BATTERY_VOLTAGE" IS '电池电压';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RESERVE1" IS '电源类型：0电池 1外供电';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RESERVE2" IS '保留位2（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RESERVE3" IS '保留位3（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RESERVE4" IS '保留位4 (未启用)';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."AVG_STD_FLOW" IS '标况流量历史均值';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."AVG_WORK_FLOW" IS '工况流量历史均值';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."AVG_TEMPERATURE" IS '温度历史均值';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."AVG_PRESSURE" IS '压力历史均值';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."COMPUTE_DAYS" IS '计算天数';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."MAG_ATT_TIMES" IS '磁攻击次数';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."MONTH_USE_VOL" IS '当月累计用量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."L1_MONTH_USE_VOL" IS '上月累计用量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."CYCLE_USE_VOL" IS '本周期累计用量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."L1_CYCLE_USE_VOL" IS '上周期累计用量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."RSSI" IS '信号强度（满格31）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."BATTERY_LEVEL" IS '电池电量';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."BASE_VOLUME" IS '表底数（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."TOTAL_BUY_VOLUME" IS '累购量（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."TOTAL_BUY_MONEY" IS '累购金额';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."EXT_DATA" IS '额外的附加数据（json）(价格完整报文)';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."CUSTOMER_NO" IS '客户编号（未启用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."TOTAL_EXPEND_MONEY" IS '累计使用金额（NB专用）';
COMMENT ON COLUMN "SCOTT"."SCADA_FLMETER_DATA_MID_DH"."SFD_STATUS" IS '1正常，9不正常已删除';
COMMENT ON TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" IS '抄表数据，从DATA表COPY，用于小时日报年报清算，提高清算速度。';

-- ----------------------------
-- Checks structure for table SCADA_FLMETER_DATA_MID_DH
-- ----------------------------
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0095142" CHECK ("SFD_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0095143" CHECK ("SFD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0095144" CHECK ("INSTANT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0095145" CHECK ("RECEIV_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0097061" CHECK ("SFD_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0097062" CHECK ("SFD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0097063" CHECK ("INSTANT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ADD CONSTRAINT "SYS_C0097064" CHECK ("RECEIV_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCADA_FLMETER_DATA_MID_DH
-- ----------------------------
CREATE INDEX "SCOTT"."FLMETER_NO_MID_DH"
  ON "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ("FLMETER_NO" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."INSTANT_TIME_MID_DH"
  ON "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ("INSTANT_TIME" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."RECEIV_TIME_MID_DH"
  ON "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ("RECEIV_TIME" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "SCOTT"."SFD_ORG_ID_MID_DH"
  ON "SCOTT"."SCADA_FLMETER_DATA_MID_DH" ("SFD_ORG_ID" ASC)
  LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
