# Generated by Django 2.1.3 on 2018-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180524_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='happen_date'),
        ),
    ]
