/*
 Navicat Premium Data Transfer

 Source Server         : Oracle LMTPlat@Server
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : server:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 10/04/2019 16:04:20
*/


-- ----------------------------
-- Table structure for ORGANIZATION
-- ----------------------------
DROP TABLE "SCOTT"."ORGANIZATION";
CREATE TABLE "SCOTT"."ORGANIZATION" (
  "ORG_ID" VARCHAR2(4 BYTE) DEFAULT '' NOT NULL ,
  "ORG_NAME" VARCHAR2(50 BYTE) DEFAULT '' ,
  "ORG_SNAME" VARCHAR2(50 BYTE) DEFAULT '' ,
  "ORG_HELPCODE" VARCHAR2(30 BYTE) DEFAULT '' ,
  "ORG_TYPE" VARCHAR2(6 BYTE) DEFAULT '' ,
  "ORG_GRADE" CHAR(1 BYTE) DEFAULT '' ,
  "ORG_MASTER" VARCHAR2(20 BYTE) DEFAULT '' ,
  "ORG_TEL" VARCHAR2(20 BYTE) DEFAULT '' ,
  "ORG_FAX" VARCHAR2(20 BYTE) DEFAULT '' ,
  "ORG_ADDRESS" VARCHAR2(100 BYTE) DEFAULT '' ,
  "ORG_ZIP" VARCHAR2(6 BYTE) DEFAULT '' ,
  "ORG_AREA" VARCHAR2(50 BYTE) DEFAULT '' ,
  "ORG_ACCT_BANK" VARCHAR2(50 BYTE) DEFAULT '' ,
  "ORG_ACCT_NAME" VARCHAR2(60 BYTE) DEFAULT '' ,
  "ORG_ACCT_NO" VARCHAR2(40 BYTE) DEFAULT '' ,
  "ORG_TAX_NO" VARCHAR2(20 BYTE) DEFAULT '' ,
  "ORG_CONTRACT_CODE" VARCHAR2(10 BYTE) DEFAULT '' ,
  "ORG_STATUS" CHAR(1 BYTE) DEFAULT '' ,
  "ORG_LASTUSERID" VARCHAR2(8 BYTE) DEFAULT '' ,
  "ORG_LASTTIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP ,
  "ORG_REPORT_GENERATE" VARCHAR2(2 BYTE) ,
  "ORG_BALANCE_BILL_GENERATE" VARCHAR2(2 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ID" IS '机构编号';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_NAME" IS '机构名称';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_SNAME" IS '机构简称';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_HELPCODE" IS '助记码';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_TYPE" IS '机构类型 0000保留 ';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_GRADE" IS '机构级别0保留机构，1公司总部';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_MASTER" IS '机构负责人';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_TEL" IS '电话';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_FAX" IS '传真';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ADDRESS" IS '地址';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ZIP" IS '邮编';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_AREA" IS '地区号';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ACCT_BANK" IS '开户行';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ACCT_NAME" IS '账户名';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_ACCT_NO" IS '账号';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_TAX_NO" IS '税号';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_CONTRACT_CODE" IS '合同编号';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_STATUS" IS '删除状态符 1 为 未删除状态 9为删除状态';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_LASTUSERID" IS '最后修改人';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_LASTTIME" IS '最后修改时间';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_REPORT_GENERATE" IS '是否计算生成报表：0不生成，1生成';
COMMENT ON COLUMN "SCOTT"."ORGANIZATION"."ORG_BALANCE_BILL_GENERATE" IS '是否计算生成账单：0不生成，1生成';

-- ----------------------------
-- Records of "ORGANIZATION"
-- ----------------------------
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0008', '东营黄河燃气', '东营黄河', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0015', '六安新奥燃气有限公司', '六安新奥燃气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0017', '上海益流天然气销售有限公司', '南汇燃气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '1');
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0005', '西宁卓然商贸有限公司', '西宁中油中泰', '西宁中油', NULL, NULL, 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0007', '太仓燃气', '太仓燃气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0009', '张家界新泰天然气有限公司', '张家界新泰', '1', '000001', '1', '赵小冬', '13307440356', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0011', '武汉东湖昆仑燃气有限公司', '武汉东湖昆仑', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0012', '武汉天然气有限公司', '武汉天然气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0016', '山西省运城市河津市江民海生燃气公司', '江民海生燃气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0019', '廊坊新奥燃气设备有限公司', '廊坊新奥燃气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2019-03-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0003', '罗美特燃气', '罗美特', '1', '000001', '1', '叶', '1684659484', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0002', '罗美特燃气', '罗美特', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0001', '罗美特股份', '罗美特', 'LMT', '000001', '1', 'LMT', '021-57588188', '021-62319751', '上海市徐汇区漕宝路', '056489', NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0000', '根机构', '根机构', 'ROOT', '000000', '0', '0', '0', '0', 'aaa', '0', 'aaa', NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-04-05 16:22:58.889000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), NULL, NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0010', '临沂华油众德燃气有限公司', '临沂华油众德', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0018', '伊川中石油昆仑燃气有限公司', '伊川中石油昆仑燃气', '1', NULL, NULL, 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0006', '黄石中石油昆仑城投燃气有限公司', '黄石中石油昆仑城投燃气有限公司', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0013', '试验天然气有限公司', '试验天然气', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', NULL);
INSERT INTO "SCOTT"."ORGANIZATION" VALUES ('0014', '兰陵中石油昆仑众德燃气有限公司', '兰陵中石油昆仑众德', '1', '000001', '1', 'A', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, TO_TIMESTAMP('2018-05-02 16:23:06.008000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', NULL);

-- ----------------------------
-- Primary Key structure for table ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."ORGANIZATION" ADD CONSTRAINT "SYS_C0011422" PRIMARY KEY ("ORG_ID");

-- ----------------------------
-- Checks structure for table ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."ORGANIZATION" ADD CONSTRAINT "SYS_C0011400" CHECK ("ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."ORGANIZATION" ADD CONSTRAINT "SYS_C0012110" CHECK ("ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."ORGANIZATION" ADD CONSTRAINT "SYS_C0013722" CHECK ("ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."ORGANIZATION" ADD CONSTRAINT "SYS_C0045896" CHECK ("ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
