/*
 Navicat Premium Data Transfer

 Source Server         : aliyun-lmtplat-公网ip-###-SCOTT-Lmt123456
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : ###:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 22/02/2019 09:26:49
*/


-- ----------------------------
-- Table structure for AREA_INFO
-- ----------------------------
DROP TABLE "SCOTT"."AREA_INFO";
CREATE TABLE "SCOTT"."AREA_INFO" (
  "AI_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "AREA_NO" VARCHAR2(50 BYTE) NOT NULL ,
  "AREA_NAME" VARCHAR2(50 BYTE) ,
  "SHORT_NAME" VARCHAR2(50 BYTE) ,
  "REMARK" VARCHAR2(50 BYTE) ,
  "AI_STATUS" CHAR(1 BYTE) DEFAULT '' 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."AI_ORG_ID" IS 'ORG-ID';
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."AREA_NO" IS '区域信息No';
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."AREA_NAME" IS '区域信息名称';
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."SHORT_NAME" IS '区域信息简称';
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."REMARK" IS '区域信息 备注';
COMMENT ON COLUMN "SCOTT"."AREA_INFO"."AI_STATUS" IS '删除标识符 1代表未删除状态 9代表删除状态';
COMMENT ON TABLE "SCOTT"."AREA_INFO" IS '区域信息';

-- ----------------------------
-- Records of "AREA_INFO"
-- ----------------------------
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0008', '0008000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0003', '0003000002', '奉贤区', NULL, NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0003', '0003000003', '徐汇区', NULL, NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0005', '0005000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0007', '0007000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0009', '0009000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0011', '0011000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0012', '0012000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000010', '1', '1', '1', '9');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000011', NULL, NULL, NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000013', 'test11', 'test21', 'test11', '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0003', '0003000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0002', '0002000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000014', '..', '.', '.', '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000001', '默认区域', '默区', '默认的区域啊！', '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000003', 'test0001', 'test', 'test', '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000002', 'demo', 'demo', 'demo1', '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000005', '黄埔区1', '黄埔区1', '黄埔区1', '9');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000004', '西安', NULL, NULL, '9');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0001', '0001000009', '请问', '请问', '请问', '9');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0010', '0010000001', '默认区域', '默区', NULL, '1');
INSERT INTO "SCOTT"."AREA_INFO" VALUES ('0006', '0006000001', '默认区域', '默区', NULL, '1');

-- ----------------------------
-- Primary Key structure for table AREA_INFO
-- ----------------------------
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012036" PRIMARY KEY ("AI_ORG_ID", "AREA_NO");

-- ----------------------------
-- Checks structure for table AREA_INFO
-- ----------------------------
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0011521" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012046" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012047" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012056" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012057" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012789" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0012790" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0013338" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0013339" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0013620" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0013621" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0018438" CHECK ("AI_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."AREA_INFO" ADD CONSTRAINT "SYS_C0018439" CHECK ("AREA_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
