/*
 Navicat Premium Data Transfer

 Source Server         : oracle-lmtplat-SCOTT-Lmt123456
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : ###:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 22/02/2019 11:22:45
*/


-- ----------------------------
-- Table structure for SHORT_MESSAGE_CONFIG
-- ----------------------------
DROP TABLE "SCOTT"."SHORT_MESSAGE_CONFIG";
CREATE TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" (
  "SMC_ORG_ID" VARCHAR2(6 BYTE) DEFAULT '' NOT NULL ,
  "SMC_CODE" VARCHAR2(6 BYTE) NOT NULL ,
  "SMC_NAME" VARCHAR2(200 BYTE) ,
  "SMC_ON" VARCHAR2(2 BYTE) DEFAULT '' ,
  "SMC_TAG1" VARCHAR2(50 BYTE) DEFAULT '' ,
  "SMC_TAG2" VARCHAR2(50 BYTE) DEFAULT '' ,
  "SMC_LASTUSERID" VARCHAR2(10 BYTE) DEFAULT '' ,
  "SMC_LASTTIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP            ,
  "SMC_STATUS" CHAR(1 BYTE) DEFAULT '' ,
  "SMC_CUSTOMER_TYPE" CHAR(4 BYTE) ,
  "SMC_TO_CUSTOMER" VARCHAR2(1 BYTE) ,
  "SMC_TO_COMPANY" VARCHAR2(1 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_ORG_ID" IS '机构号';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_CODE" IS '4位流水编码，使用场景区分';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_NAME" IS '名称';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_ON" IS '是否启用，0否1是';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_TAG1" IS '参数1,下限';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_TAG2" IS '参数2,上限';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_LASTUSERID" IS '修改人';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_LASTTIME" IS '修改时间';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_STATUS" IS '状态';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_CUSTOMER_TYPE" IS '客户类型，IDBOOKS5';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_TO_CUSTOMER" IS '是否发送客户';
COMMENT ON COLUMN "SCOTT"."SHORT_MESSAGE_CONFIG"."SMC_TO_COMPANY" IS '是否发送燃气公司';

-- ----------------------------
-- Records of "SHORT_MESSAGE_CONFIG"
-- ----------------------------
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0001', '欠费', '1', '1000', NULL, '00030002', TO_TIMESTAMP('2019-01-24 17:32:14.061000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0003', '1', '1');
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0002', '一般报警：断电…', '1', NULL, NULL, '00030002', TO_TIMESTAMP('2019-01-24 17:32:02.093000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0003', '1', '0');
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0003', '非常报警，涉嫌盗气、不正常使用。', '1', NULL, NULL, '0003', TO_TIMESTAMP('2019-01-24 09:32:08.960000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0003', '0', '0');
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0004', '欠费', '1', '10', NULL, '00030002', TO_TIMESTAMP('2019-01-24 17:32:14.061000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0001', '1', '1');
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0005', '一般报警：断电…', '1', NULL, NULL, '00030002', TO_TIMESTAMP('2019-01-24 17:32:02.093000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0001', '1', '0');
INSERT INTO "SCOTT"."SHORT_MESSAGE_CONFIG" VALUES ('0003', '0006', '非常报警，涉嫌盗气、不正常使用。', '1', NULL, NULL, '0003', TO_TIMESTAMP('2019-01-24 09:32:08.960000', 'SYYYY-MM-DD HH24:MI:SS:FF6'), '1', '0001', '0', '0');

-- ----------------------------
-- Primary Key structure for table SHORT_MESSAGE_CONFIG
-- ----------------------------
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0025176" PRIMARY KEY ("SMC_ORG_ID", "SMC_CODE");

-- ----------------------------
-- Checks structure for table SHORT_MESSAGE_CONFIG
-- ----------------------------
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0025170" CHECK ("SMC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0025171" CHECK ("SMC_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0036834" CHECK ("SMC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0036835" CHECK ("SMC_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0036836" CHECK ("SMC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0036837" CHECK ("SMC_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0038889" CHECK ("SMC_ORG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."SHORT_MESSAGE_CONFIG" ADD CONSTRAINT "SYS_C0038890" CHECK ("SMC_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
